<?php

namespace App\DataTransferObjects;

use App\Models\PaymentIntention;
use App\Repositories\PaymentRepository;

class PaymobWebhookData
{
    private array $data;
    private array $obj;
    private array $order;
    private array $sourceData;
    private array $paymentKeyClaims;
    private array $extras;
    private ?PaymentIntention $cachedIntention = null;

    public function __construct(array $webhookData)
    {
        $this->data = $webhookData;
        $this->obj = $webhookData['obj'] ?? [];
        $this->order = $this->obj['order'] ?? [];
        $this->sourceData = $this->obj['source_data'] ?? [];
        $this->paymentKeyClaims = $this->obj['payment_key_claims'] ?? [];
        $this->extras = $this->paymentKeyClaims['extra'] ?? [];
    }

    /**
     * Transaction ID from Paymob (obj.id)
     *
     * Note: This is the transaction ID generated by Paymob AFTER payment processing.
     * We don't receive this in the initial intention request - only in the webhook callback.
     * Example: 1028235
     */
    public function getTransactionId(): ?string
    {
        return $this->obj['id'] ?? null;
    }

    /**
     * Order ID from Paymob (order.id)
     *
     * Note: This is the order ID in Paymob that we receive in the intention request.
     * Also known as paymob_order_id in our database.
     * Example: 1059186
     */
    public function getOrderId(): ?string
    {
        return $this->order['id'] ?? null;
    }

    /**
     * Custom merchant order ID (order.merchant_order_id)
     *
     * Note: This is OUR custom order ID that we create and send in the intention request.
     * Used to uniquely identify transactions in our system.
     * Example: "WALLET-CHARGE-15-1760700181" or "INV-1-15-1760700181"
     */
    public function getMerchantOrderId(): ?string
    {
        return $this->order['merchant_order_id'] ?? null;
    }

    /**
     * Paymob integration ID
     *
     * Note: This is the integration ID in Paymob that we receive in the intention request.
     * Identifies which payment integration (card, wallet, etc.) was used.
     * Example: 16105
     */
    public function getIntegrationId(): ?int
    {
        return $this->obj['integration_id'] ?? null;
    }

    /**
     * Paymob profile ID
     *
     * Note: This is the profile ID for our merchant account in Paymob.
     * Remains constant across all transactions for our account.
     * Example: 11883
     */
    public function getProfileId(): ?int
    {
        return $this->obj['profile_id'] ?? null;
    }

    /**
     * Payment method (e.g., "MasterCard", "Visa")
     *
     * Extracted from source_data.sub_type (preferred) or source_data.type (fallback)
     * Examples: "MasterCard", "Visa", "Mada"
     */
    public function getPaymentMethod(): ?string
    {
        return $this->sourceData['sub_type'] ?? $this->sourceData['type'] ?? null;
    }

    /**
     * Card last 4 digits (PAN)
     *
     * Example: "2346" (from card number 512345xxxxxx2346)
     */
    public function getCardPan(): ?string
    {
        return $this->sourceData['pan'] ?? null;
    }

    /**
     * Check if transaction was successful
     *
     * Returns true if obj.success === true
     * This is the primary indicator that payment was completed successfully.
     */
    public function isSuccessful(): bool
    {
        return ($this->obj['success'] ?? false) === true;
    }

    /**
     * Check if transaction is pending
     *
     * Returns true if obj.pending === true
     * Indicates payment is still being processed.
     */
    public function isPending(): bool
    {
        return ($this->obj['pending'] ?? false) === true;
    }

    /**
     * Check if transaction is a refund
     *
     * Returns true if obj.is_refund === true
     * Indicates this webhook is for a refund operation.
     */
    public function isRefund(): bool
    {
        return ($this->obj['is_refund'] ?? false) === true;
    }

    /**
     * Check if transaction has been refunded
     *
     * Returns true if obj.is_refunded === true
     * Indicates the original transaction was refunded.
     */
    public function isRefunded(): bool
    {
        return ($this->obj['is_refunded'] ?? false) === true;
    }

    /**
     * Get transaction status string
     *
     * Returns: "successful", "pending", or "failed"
     * Based on obj.success and obj.pending flags
     */
    public function getStatus(): string
    {
        if ($this->isSuccessful()) {
            return 'successful';
        }

        if ($this->isPending()) {
            return 'pending';
        }

        return 'failed';
    }

    /**
     * Get intention status for database
     *
     * Maps Paymob status to our database status:
     * - successful → completed
     * - pending → pending
     * - failed → failed
     */
    public function getIntentionStatus(): string
    {
        return match($this->getStatus()) {
            'successful' => 'completed',
            'pending' => 'pending',
            default => 'failed'
        };
    }

    /**
     * Amount in cents (smallest currency unit)
     *
     * Example: 10000 (represents 100.00 SAR)
     * All Paymob amounts are in cents (fils in Arabic)
     */
    public function getAmountCents(): ?int
    {
        return $this->obj['amount_cents'] ?? null;
    }

    /**
     * Amount in SAR (Saudi Riyal)
     *
     * Converts cents to SAR by dividing by 100
     * Example: 10000 cents → 100.00 SAR
     */
    public function getAmountSar(): float
    {
        return ($this->getAmountCents() ?? 0) / 100;
    }

    /**
     * Paid amount in cents
     *
     * The actual amount paid by the customer (from order)
     * May differ from amount_cents in case of partial payments
     */
    public function getPaidAmountCents(): int
    {
        return $this->order['paid_amount_cents'] ?? 0;
    }

    /**
     * Currency code
     *
     * Usually "SAR" for Saudi Riyal
     * Checked from order.currency first, then obj.currency
     */
    public function getCurrency(): ?string
    {
        return $this->order['currency'] ?? $this->obj['currency'] ?? null;
    }

    /**
     * Payment status from order
     *
     * Expected to be "PAID" for successful payments
     * Other possible values: "PENDING", "FAILED", "REFUNDED"
     */
    public function getPaymentStatus(): ?string
    {
        return $this->order['payment_status'] ?? null;
    }

    /**
     * Check if payment status is "PAID"
     *
     * This is a secondary confirmation alongside obj.success
     */
    public function isPaid(): bool
    {
        return $this->getPaymentStatus() === 'PAID';
    }

    /**
     * User ID from payment key claims
     *
     * This is OUR system's user ID (from users table)
     * Passed in payment_key_claims.extra.user_id
     * Example: 15
     */
    public function getUserId(): ?int
    {
        return $this->paymentKeyClaims['extra']['user_id'];
    }

    /**
     * Get opportunity ID from extras (for investments)
     *
     * Our system's investment_opportunity_id
     * Only present when operation_type is "investment"
     * Example: 42
     */
    public function getOpportunityId(): ?int
    {
        return $this->extras['opportunity_id'] ?? null;
    }

    /**
     * Get all extras data
     *
     * Contains custom data we passed in payment_key_claims.extra:
     * - user_id: Our user ID
     * - amount_sar: Amount in SAR
     * - operation_type: "wallet_charge" or "investment"
     * - merchant_order_id: Our custom order ID
     * - opportunity_id: (for investments only)
     * - shares: (for investments only)
     * - investment_type: (for investments only)
     */
    public function getExtras(): array
    {
        return $this->extras;
    }

    /**
     * Get full webhook data
     */
    public function getRawData(): array
    {
        return $this->data;
    }

    /**
     * Get obj data
     */
    public function getObj(): array
    {
        return $this->obj;
    }

    /**
     * Get order data
     */
    public function getOrder(): array
    {
        return $this->order;
    }

    /**
     * Get source data
     */
    public function getSourceData(): array
    {
        return $this->sourceData;
    }

    /**
     * Get payment key claims
     */
    public function getPaymentKeyClaims(): array
    {
        return $this->paymentKeyClaims;
    }

    /**
     * Get webhook type
     *
     * Paymob sends different webhook types:
     * - "TRANSACTION" - Payment transaction completed
     * - "TOKEN" - Card tokenization completed
     * - "DELIVERY_STATUS" - Delivery status update
     */
    public function getType(): ?string
    {
        return $this->data['type'] ?? null;
    }

    /**
     * Check if this is a transaction webhook
     *
     * Returns true for payment transactions
     * This is the most common webhook type we process
     */
    public function isTransactionWebhook(): bool
    {
        return $this->getType() === 'TRANSACTION';
    }

    /**
     * Check if this is a token webhook
     *
     * Returns true for card tokenization webhooks
     * Used when saving customer cards for future use
     */
    public function isTokenWebhook(): bool
    {
        return $this->getType() === 'TOKEN';
    }

    /**
     * Validate required fields
     *
     * Checks that webhook contains minimum required data:
     * - Transaction ID (obj.id) - Generated by Paymob after payment
     * - Order ID (order.id) - Our paymob_order_id from intention
     */
    public function isValid(): bool
    {
        return !empty($this->getTransactionId())
            && !empty($this->getOrderId());
    }

    /**
     * Get validation errors
     *
     * Returns array of error messages if validation fails
     * Empty array means validation passed
     */
    public function getValidationErrors(): array
    {
        $errors = [];

        if (empty($this->getTransactionId())) {
            $errors[] = 'Missing transaction ID (obj.id) - Paymob did not provide transaction identifier';
        }

        if (empty($this->getOrderId())) {
            $errors[] = 'Missing order ID (order.id) - Cannot match webhook to payment intention';
        }

        return $errors;
    }

    /**
     * Convert to array for database storage
     *
     * Prepares data for PaymentRepository to find and update payment intentions
     * Maps Paymob webhook data to our database columns
     */
    public function toTransactionArray(): array
    {
        return [
            'transaction_id' => $this->getTransactionId(),      // For payment_intentions.transaction_id
            'order_id' => $this->getOrderId(),                  // For payment_intentions.paymob_order_id
            'merchant_order_id' => $this->getMerchantOrderId(), // For payment_intentions.special_reference
            'payment_method' => $this->getPaymentMethod(),      // For payment_intentions.payment_method
            'status' => $this->getStatus(),                     // For determining intention status
            'paymob_response' => $this->getRawData(),           // For payment_intentions.paymob_response (JSON)
        ];
    }

    /**
     * Verify webhook authenticity and data integrity
     *
     * Performs comprehensive verification:
     * 1. HMAC signature validation (if secret provided)
     * 2. Required fields validation
     * 3. Data consistency checks
     * 4. Amount validation
     * 5. Status coherence checks
     *
     * @param string|null $hmacSecret The HMAC secret from Paymob config
     * @return array ['valid' => bool, 'errors' => array, 'warnings' => array]
     */
    public function verify(?string $hmacSecret = null): array
    {
        $errors = [];
        $warnings = [];

        // 1. HMAC Verification (if secret provided)
        // if ($hmacSecret && isset($this->data['hmac'])) {
        //     $receivedHmac = $this->data['hmac'];
        //     $calculatedHmac = $this->calculateHmac($hmacSecret);

        //     if ($receivedHmac !== $calculatedHmac) {
        //         $errors[] = 'HMAC verification failed - webhook may not be authentic';
        //     }
        // } elseif ($hmacSecret && !isset($this->data['hmac'])) {
        //     $warnings[] = 'HMAC not provided in webhook data';
        // }

        // 1.1. Check if the webhook has PaymentIntention
        if (!$this->hasPaymentIntention()) {
            $errors[] = 'No payment intention found for this webhook';
        }

        // 1.2. Check if PaymentIntention is executed
        if ($this->getPaymentIntention()->is_executed) {
            $errors[] = 'Payment intention already executed';
        }


        // 2. Required Fields Validation
        $validationErrors = $this->getValidationErrors();
        if (!empty($validationErrors)) {
            $errors = array_merge($errors, $validationErrors);
        }

        // 3. Transaction Type Check
        if (!$this->isTransactionWebhook()) {
            $warnings[] = sprintf('Unexpected webhook type: %s', $this->getType());
        }

        // 4. Amount Validation
        $amountCents = $this->getAmountCents();
        $paidAmountCents = $this->getPaidAmountCents();

        if ($amountCents === null || $amountCents <= 0) {
            $errors[] = 'Invalid amount: must be greater than 0';
        }

        if ($paidAmountCents > 0 && $amountCents !== $paidAmountCents) {
            $warnings[] = sprintf(
                'Amount mismatch: amount_cents=%d, paid_amount_cents=%d',
                $amountCents,
                $paidAmountCents
            );
        }

        // 5. Currency Validation
        $currency = $this->getCurrency();
        if (empty($currency)) {
            $errors[] = 'Missing currency code';
        } elseif ($currency !== 'SAR') {
            $warnings[] = sprintf('Unexpected currency: %s (expected SAR)', $currency);
        }



        // 6. Status Coherence Checks
        if ($this->isSuccessful()) {
            // Successful payment should be PAID
            if (!$this->isPaid()) {
                $warnings[] = sprintf(
                    'Status inconsistency: success=true but payment_status=%s',
                    $this->getPaymentStatus()
                );
            }

            // Successful payment should not be pending
            if ($this->isPending()) {
                $errors[] = 'Invalid state: transaction cannot be both successful and pending';
            }
        }else{
            $errors[] = 'Transaction failed';
        }

        // 7. Refund Validation
        if ($this->isRefund() && $this->isSuccessful()) {
            $warnings[] = 'Refund transaction marked as successful - verify this is expected';
        }

        // 8. Integration & Profile ID Checks
        if (!$this->getIntegrationId()) {
            $warnings[] = 'Missing integration_id';
        }

        if (!$this->getProfileId()) {
            $warnings[] = 'Missing profile_id';
        }

        // 9. Payment Method Validation
        if (empty($this->getPaymentMethod())) {
            $warnings[] = 'Missing payment method information';
        }

        // 10. User ID Check
        if (!$this->getUserId()) {
            $warnings[] = 'Missing user_id - cannot identify transaction owner';
        }

        // // 11. Operation Type Check (custom field)
        // if (!$this->getOperationType()) {
        //     $warnings[] = 'Missing operation_type in extras - transaction type unclear';
        // }

        return [
            'valid' => empty($errors),
            'errors' => $errors,
            'warnings' => $warnings,
            'summary' => $this->getVerificationSummary(empty($errors), $errors, $warnings)
        ];
    }

    /**
     * Calculate HMAC signature for webhook verification
     *
     * Uses Paymob's HMAC calculation method
     *
     * @param string $hmacSecret The HMAC secret from Paymob
     * @return string The calculated HMAC hash
     */
    private function calculateHmac(string $hmacSecret): string
    {
        $obj = $this->getObj();

        // Paymob HMAC calculation uses specific fields in order
        $concatenatedString =
            ($obj['amount_cents'] ?? '') .
            ($obj['created_at'] ?? '') .
            ($obj['currency'] ?? '') .
            ($obj['error_occured'] ?? 'false') .
            ($obj['has_parent_transaction'] ?? 'false') .
            ($obj['id'] ?? '') .
            ($obj['integration_id'] ?? '') .
            ($obj['is_3d_secure'] ?? 'false') .
            ($obj['is_auth'] ?? 'false') .
            ($obj['is_capture'] ?? 'false') .
            ($obj['is_refunded'] ?? 'false') .
            ($obj['is_standalone_payment'] ?? 'false') .
            ($obj['is_voided'] ?? 'false') .
            ($obj['order']['id'] ?? '') .
            ($obj['owner'] ?? '') .
            ($obj['pending'] ?? 'false') .
            ($obj['source_data']['sub_type'] ?? 'NA') .
            ($obj['source_data']['pan'] ?? 'NA') .
            ($obj['source_data']['type'] ?? 'NA') .
            ($obj['success'] ?? '');

        return hash_hmac('sha512', $concatenatedString, $hmacSecret);
    }

    /**
     * Get verification summary message
     */
    private function getVerificationSummary(bool $valid, array $errors, array $warnings): string
    {
        if ($valid && empty($warnings)) {
            return sprintf(
                'Webhook verified successfully: %s',
                $this->__toString()
            );
        }

        if ($valid && !empty($warnings)) {
            return sprintf(
                'Webhook valid with %d warning(s): %s',
                count($warnings),
                $this->__toString()
            );
        }

        return sprintf(
            'Webhook verification failed with %d error(s) and %d warning(s)',
            count($errors),
            count($warnings)
        );
    }

    /**
     * Find and return the related PaymentIntention
     *
     * Searches for the payment intention using:
     * 1. paymob_order_id (order.id from webhook)
     * 2. special_reference (merchant_order_id)
     * 3. transaction_id (if duplicate webhook)
     *
     * Results are cached to avoid multiple database queries
     *
     * @return PaymentIntention|null The related payment intention or null if not found
     */
    public function getPaymentIntention(): ?PaymentIntention
    {
        // Return cached result if already fetched
        // if ($this->cachedIntention !== null) {
        //     return $this->cachedIntention;
        // }

        // Get repository instance
        $repository = app(PaymentRepository::class);

        // Try to find intention using webhook data
        $this->cachedIntention = $repository->findIntentionFromWebhook($this->toTransactionArray());

        return $this->cachedIntention;
    }

    /**
     * Check if a related PaymentIntention exists
     *
     * @return bool True if payment intention found, false otherwise
     */
    public function hasPaymentIntention(): bool
    {
        return $this->getPaymentIntention() !== null;
    }

    /**
     * Get PaymentIntention ID if it exists
     *
     * @return int|null The payment intention ID or null
     */
    public function getPaymentIntentionId(): ?int
    {
        $intention = $this->getPaymentIntention();
        return $intention?->id;
    }

    /**
     * Clear cached payment intention
     *
     * Useful if you need to re-fetch the intention after updates
     *
     * @return self
     */
    public function clearIntentionCache(): self
    {
        $this->cachedIntention = null;
        return $this;
    }

    /**
     * Magic method for debugging and logging
     *
     * Provides a human-readable representation of the webhook
     * Example: "PaymobWebhook[transaction_id=1028235, order_id=1059186, status=successful, amount=100 SAR]"
     */
    public function __toString(): string
    {
        return sprintf(
            'PaymobWebhook[transaction_id=%s, order_id=%s, merchant_order_id=%s, status=%s, amount=%s SAR, method=%s]',
            $this->getTransactionId(),
            $this->getOrderId(),
            $this->getMerchantOrderId(),
            $this->getStatus(),
            number_format($this->getAmountSar(), 2),
            $this->getPaymentMethod()
        );
    }
}

